//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanlaptop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TINTUC
    {
        public int MATT { get; set; }
        public string TENTT { get; set; }
        public string MOTA { get; set; }
        public string HINHTT { get; set; }
        public string NOIDUNG { get; set; }
        public bool TRANGTHAI { get; set; }
    }
}
